name: Deploy production

on:
  push:
    branches:
      - 'master'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/express-todo:prod

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE_NAME }}-$SHA8
          push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.TARGET_REPO }}
        token: ${{ secrets.PAT_FOR_PUSH }}
        ref: master

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"

    - name: Update Kubernetes resources
      run: |
       cd overlays/prod
       kustomize edit set image $IMAGE_NAME-$SHA8
       cd ...
       kustomize build overlays/prod > manifest/prod/manifest.yml

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "Bump docker prod tag"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ secrets.TARGET_REPO }}
        github_token: ${{ secrets.PAT_FOR_PUSH }}
        branch: master
