name: Deploy production

on:
  push:
    branches:
      - 'master'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      SHA7: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      SHA7: ${{ needs.prepare.outputs.SHA7 }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-todo:prod-${{ env.SHA7 }}
          push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [prepare, build]
    env:
      SHA7: ${{ needs.prepare.outputs.SHA7 }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.TARGET_REPO }}
        token: ${{ secrets.PAT_FOR_PUSH }}
        ref: master-build

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"

    - name: Pulling code
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master --allow-unrelated-histories --ff-only --no-edit

    - name: Update Kubernetes resources and commit
      run: |
        cd overlays/prod
        kustomize edit set image $DOCKERHUB_USERNAME/express-todo:prod-$SHA7
        cd -
        kustomize build overlays/prod > manifest/prod/manifest.yml
        git add .
        git commit -am "Bump docker prod tag $SHA7"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ secrets.TARGET_REPO }}
        github_token: ${{ secrets.PAT_FOR_PUSH }}
        branch: master-build
